### ISSUE TITLE
有es6版本的吗, 发现只有ts版本的

### ISSUE THREAD

**Issue by liaohui1080** [xxapp/msBus#18]
有es6版本的吗, 发现只有ts版本的

**Comment by xxapp** [comment]
正打算转换到 es 版本

**Comment by xxapp** [comment]
已转

**Comment by liaohui1080** [comment]
@xxapp 请问 什么时候转的 ,代码库在哪

**Comment by xxapp** [comment]
@liaohui1080 就在这个仓库，看提交记录，因为原本 ts 的语法用的不是很多，所以改了下构建配置，去掉 ts 的语法使用很快就改了。
