### ISSUE TITLE
ie8无法打开

### ISSUE THREAD

**Issue by iamllitog** [xxapp/msBus#19]
ie8控制台报错如下
![image](https://user-images.githubusercontent.com/6738756/28707660-cfff8f48-73ab-11e7-945d-813571e217cd.png)

**Comment by xxapp** [comment]
非常感谢指出这个问题！

使用 babel 的三个插件解决了这个问题 `['transform-es3-property-literals', 'transform-es3-member-expression-literals', 'add-module-exports']`

以前用 typescript 是自动处理的，迁移到 es6 才有的这个问题。
