### ISSUE TITLE
ms-bus的fis3配置amd

### ISSUE THREAD

**Issue by xieminhui** [xxapp/msBus#20]
我将fis原本的hook配置改为了amd，不用commonjs这个时候会报错，想问下这框架可以将commonjs改成amd吗？

**Comment by xxapp** [comment]
理论上可以的，你可以参考 fis 教程试一下，不过要改的东西可能有点多。

**Comment by xieminhui** [comment]
modJS只实现了AMD的一个子集，如果需要使用完整兼容AMD规范的版本，请使用amd目录下的esl-mod.js。框架配合commonjs一起使用的时候，默认用的是modjs，如果我想使用esl-mod.js，这个改如何配置呢？

**Comment by xxapp** [comment]
这个脚手架只是一个参考，如果你想用 amd 的方式组织代码，完全可以自己搭一个基于 amd 的框架，ms-bus 你觉得有用的东西可以直接移植过去。
