### ISSUE TITLE
avalon 升级到 2.2.6，报错

### ISSUE THREAD

**Issue by hmfw** [xxapp/msBus#8]
刚才clone下来后，发现有报错问题，也不知道该如何解决，可以加我QQ（970426404）帮忙解决下吗

**Comment by xxapp** [comment]
可以简单描述下你的问题吗，报了什么错呢？nodejs 记得用 6.x 的版本哦。

**Comment by xxapp** [comment]
![5d40ad93-5b91-48ed-aab4-796e6941d579](https://cloud.githubusercontent.com/assets/5040144/25646052/e32359fa-2fe6-11e7-8962-d30bb46d37b9.png)

dashboard 页面会报上面这个错，2.2.5 是没有问题的，已经确定是 avalon 本身的问题。

**Comment by xxapp** [comment]
https://github.com/RubyLouvre/avalon/issues/1985

https://github.com/RubyLouvre/avalon/issues/1987

给avalon提了pr，已经被合并了，等avalon升级到2.2.7就会修复此问题

在此之前可以用 avalon 2.2.5

**Comment by xxapp** [comment]
https://github.com/RubyLouvre/avalon/releases/tag/v2.2.7

avalon 2.2.7 已经发布
